Parallel app
sergey-berezin/406_vasilchenko pull request #3
Opened 2024-10-14 13:34 UTC by VasilchenkoDmitrii03

Добавлено приложение для визуализации, в нем можно сделать свою матрицу для городов (до 10 городов), если хотите больше городов, то матрица просто не отображается, но создаётся. Можно выбрать количество сущностей в одном поколении, по запуску начинается поиск оптимального маршрута.

2024-10-15 10:30 UTC, sergey-berezin commented
В PR есть лишняя папка .vs

2024-10-18 13:46 UTC, VasilchenkoDmitrii03 commented
Здравствуйте, исправил

2024-10-22 08:51 UTC, sergey-berezin commented
Посмотрите четыре комментария к исходному коду.

2024-10-24 07:56 UTC, VasilchenkoDmitrii03 commented
Можете подсказать где их смотреть, я вообще найти не могу

2024-10-24 12:32 UTC, sergey-berezin commented
На вкладке Conversation.

![image](https://github.com/user-attachments/assets/1e7a4f72-e0a6-4417-bfa7-266bb073969b)

2024-10-24 12:45 UTC, VasilchenkoDmitrii03 commented
У меня это не отображается по какой-то причине
![image](https://github.com/user-attachments/assets/45fcc804-59c7-4f28-96ea-231ed42baed5)

2024-11-08 09:42 UTC, sergey-berezin commented
Дмитрий, приходите в понедельник 11 ноября в 9:45 в ауд. 705. Разберёмся с проблемой до лекции.

2024-11-11 06:46 UTC, sergey-berezin requested changes

2024-11-11 06:46 UTC, sergey-berezin commented on GeneticAlg/VisualisationApp/MatrixControl.xaml.cs
> +            if (count > 7)
Почему здесь ограничение?

2024-11-11 06:46 UTC, sergey-berezin commented on GeneticAlg/VisualisationApp/MainWindow.xaml.cs
> +            await Task.Run(() =>
Надо использовать опцию LongRunningTask, которая доступна в Task.StartNew

2024-11-11 06:46 UTC, sergey-berezin commented on GeneticAlg/VisualisationApp/MainWindow.xaml.cs
> +                    if(currentEpoch % 1 == 0)
Т.е. для каждой итерации?

2024-11-11 06:46 UTC, sergey-berezin commented on GeneticAlg/VisualisationApp/MainWindow.xaml.cs
> +        public async void visualisation(Route best)
Имена методов надо начинать с большой буквы

2024-11-11 06:56 UTC, VasilchenkoDmitrii03 commented
Исправил

2024-11-11 13:05 UTC, merged